name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip  # This path is specific to Ubuntu
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip requirements
        timeout-minutes: 2
        run: |
          # Now, install dependencies.
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install mypy

      - name: Check types
        run: mypy perceptual_advex/*.py *.py
        if: ${{ always() }}
